name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build complete
        run: echo "✅ Build and tests passed successfully!"

  simulate_deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: success()
    steps:
      - name: Simulate Deployment
        run: |
          echo "🚀 Simulating deployment..."
          echo "Application would now be deployed to the server."
          echo "✅ CI/CD pipeline completed successfully."
